# Read the documentation: https://github.com/roukmoute/HashidsBundle/blob/master/README.md
roukmoute_hashids:
    salt:            ""
    min_hash_length: 8
    alphabet:        "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890"
    passthrough:     false
