vich_uploader:
    db_driver: orm

    mappings:
        bl_document:
            uri_prefix: /documents/livraisons
            upload_destination: '%kernel.project_dir%/public/documents/livraisons'

